name: CI

on:
  push:
    branches:
      - main # Adjust this to your main branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Run tests
        run: ./test.sh
